### ISSUE TITLE
Interaction type

### ISSUE THREAD

**Issue by boyanghust** [Tushar-N/interaction-hotspots#2]
Whether the provided pre-training model can only recognize the type of interaction in the code. For example: Can the epic model recognize dry, turn, and other affordances? Thanks for your help.

**Comment by Tushar-N** [comment]
The model is trained for all EPIC verbs, so you could potentially just change the verb you pass to the [generate_cams(img, verbs)](https://github.com/Tushar-N/interaction-hotspots/blob/932cb582327b19b7ad10a165a3cb8e41cb5fb43d/eval.py#L75) function to be any EPIC class.
```
masks = gcam.generate_cams(img.cuda(), [verb]) # (B, T, C, 7, 7)
```

We evaluated the EPIC model on only a set of frequent afforded actions. The other verbs in the tail of the distribution do not have as much training data, and don't produce well localized hotspots.

**Comment by boyanghust** [comment]
Thank you for your help, it is very helpful.
