### ISSUE TITLE
How to choose a separate heat map

### ISSUE THREAD

**Issue by boyanghust** [Tushar-N/interaction-hotspots#3]
Thank you very much for your meaningful research. I want to combine your research with robot control.
My problem is that I want to get the heat map for each action individually.
For example, for OPRA：
cmap = torch.zeros(hmaps.shape)
Does cmap[0] represent the first action (hold)?
Or is there a way I can get the heap map for each action?
Thank you again

**Comment by Tushar-N** [comment]
Yes, cmap is a `(C, H, W)` tensor where the first dimension iterates over action classes in OPRA.

**Comment by boyanghust** [comment]
Furthermore, whether each item of CMAP is for a specific action, for example: for OPRA
Model, in different images, cmap[0] always represents ''hold'', cmap[1] always represents ''rotate''. Because I found that when I visualized the heat map of each action separately, the area corresponding to the interactive heat map was not completely consistent.
Thanks for your help.
