### ISSUE TITLE
Missing last frame

### ISSUE THREAD

**Issue by mkt1412** [Tushar-N/interaction-hotspots#5]
Hi,

I have got the eval.py and viz.py running but one error occurs during training. It says for some clips, the last frame cannot be found. It only happens on a small portion of clips and typically last frames. I assume this comes from incorrect frames extraction using extract_opra_frames.py. Any ideas? Thanks! 

Some error message are as below:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/chao/GitHub_repo/opra/data/frames/appliances/17/1/116.3_1.5.mp4/image-00000008.jpg'`
`FileNotFoundError: [Errno 2] No such file or directory: '/home/chao/GitHub_repo/opra/data/frames/appliances/8/1/35.5_0.9.mp4/image-00000005.jpg'`
`FileNotFoundError: [Errno 2] No such file or directory: '/home/chao/GitHub_repo/opra/data/frames/eguru/1/24/108.3_1.5.mp4/image-00000008.jpg'`
`FileNotFoundError: [Errno 2] No such file or directory: '/home/chao/GitHub_repo/opra/data/frames/appliances/9/9/28.9_1.5.mp4/image-00000008.jpg'`

**Comment by Tushar-N** [comment]
Maybe it's the ffmpeg version? I believe I used ffmpeg 4.2 for this project, but I would try versions ~2019 if this is an issue.

**Comment by mkt1412** [comment]
> Maybe it's the ffmpeg version? I believe I used ffmpeg 4.2 for this project, but I would try versions ~2019 if this is an issue.

Hi,

Thanks for the fast reply. I tried several versions of ffmpeg including 4.2 on several machines, but none of them worked. Is this possible to downaload the segmented data directly somewhere? Thanks!

**Comment by Tushar-N** [comment]
I don't have the data pre-extracted on any machines. Maybe it's a good idea to follow the instructions on the Demo2vec [github repo](https://github.com/kuanfang/opra) for the OPRA frames.
