### ISSUE TITLE
Forbidden visit data download link

### ISSUE THREAD

**Issue by chenjoya** [Tushar-N/interaction-hotspots#8]
Hi Tushar, thank you for your excellent work. Could you update the data download link? (https://www.cs.utexas.edu/~tushar/interaction-hotspots/hotspot_data.tar.gz)? It hints that "you don't have permission to access this resource".

**Comment by Tushar-N** [comment]
Sorry about that - I recently moved data around and missed updating the links. It's on Google Drive now: [link](https://drive.google.com/file/d/1RvlMf9tv6Hi5oNE9xtG18x7uDoBAWqJz/view?usp=sharing )
